import { NewsArticle } from '@/types';

const now = Date.now();

export const FALLBACK_ARTICLES: NewsArticle[] = [
  {
    id: 'fallback-top-story',
    title: 'Leafs newsroom is ready for the next major story',
    description: 'The aggregator is configured to monitor official sources, major sports desks, hockey sites, Leafs blogs, podcasts, video channels, radio, and TV clips.',
    source: 'TML Today',
    sourceUrl: '/',
    link: '/news',
    contentType: 'article',
    publishedAt: new Date(now - 20 * 60 * 1000).toISOString(),
    category: 'Newsroom',
    aiSummary: 'TML Today is configured as an AI-assisted Leafs newsroom, ready to summarize and classify new stories as they are discovered.',
    keyTakeaways: ['Sources are grouped by official, newspaper, sports media, hockey sites, Leafs blogs, podcasts, video, radio, and TV.', 'Stories receive topic, player, coach, rumour, sentiment, tag, duplicate, and importance metadata.', 'The refresh endpoint can be triggered every 10 minutes from Cloudflare.'],
    players: ['Auston Matthews', 'Mitch Marner'],
    coaches: ['Craig Berube'],
    topic: 'breaking',
    isRumour: false,
    rumourConfidence: 0,
    sentiment: 'neutral',
    tags: ['newsroom', 'aggregator', 'leafs'],
    duplicateOf: null,
    importance: 92,
  },
  {
    id: 'fallback-rumour-watch',
    title: 'Rumour watch will separate speculation from confirmed Leafs news',
    description: 'Rumour scoring weighs source reliability, language signals, and confirmation language so readers can understand how much confidence to place in a report.',
    source: 'TML Today',
    sourceUrl: '/',
    link: '/news?topic=rumour',
    contentType: 'article',
    publishedAt: new Date(now - 55 * 60 * 1000).toISOString(),
    category: 'Rumour',
    aiSummary: 'Rumour confidence scoring is available for trade and roster speculation, with clear flags when a story is not yet confirmed.',
    keyTakeaways: ['Hedged language lowers confidence.', 'Reliable sources and confirmation language raise confidence.', 'Rumours stay visually separated from confirmed news.'],
    players: ['William Nylander'],
    coaches: [],
    topic: 'rumour',
    isRumour: true,
    rumourConfidence: 58,
    sentiment: 'neutral',
    tags: ['rumour-watch', 'trade', 'confidence'],
    duplicateOf: null,
    importance: 78,
  },
  {
    id: 'fallback-video',
    title: 'Video and podcast items flow into the same story intelligence layer',
    description: 'Episodes, clips, interviews, and radio segments are indexed individually and can appear beside related articles.',
    source: 'TML Today',
    sourceUrl: '/',
    link: '/videos',
    contentType: 'video',
    publishedAt: new Date(now - 90 * 60 * 1000).toISOString(),
    category: 'Media',
    aiSummary: 'The aggregator treats video, podcast, radio, and TV clips as first-class newsroom items instead of separate silos.',
    keyTakeaways: ['Media gets player tags and topic labels.', 'Related videos and podcasts can attach to story pages.', 'The homepage can feature media sections automatically.'],
    players: ['Auston Matthews'],
    coaches: [],
    topic: 'media',
    isRumour: false,
    rumourConfidence: 0,
    sentiment: 'positive',
    tags: ['video', 'podcast', 'media'],
    duplicateOf: null,
    importance: 64,
  },
];
